services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://postgres:12345678a@postgres:5432/image_db
      - ACCESS_KEY=RtHAv-8Fg8V-4HRR_oVzLe5tblK_PQ6U52tbmYYB0dY
      - BASE_URL=https://api.unsplash.com/search/photos/
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
  postgres:
    image: postgres:latest
    container_name: nestjs-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678a
      POSTGRES_DB: image_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "543:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

volumes:
  postgres_data:
